# Generated by Django 6.0.5 on 2026-06-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_productbatch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
