# Generated by Django 6.0.5 on 2026-06-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('delivered', 'Доставлен'), ('canceled', 'Отменён')], max_length=100),
        ),
    ]
